id = "flow-icons"
name = "Flow Icons"
version = "2.0.3"
schema_version = 1
authors = ["thang-nm <thang-nm>"]
description = "A premium icon pack for Zed, ported from Flow Icons for VSCode"
repository = "https://github.com/Y-ASLant/Flow-Icons-Zed"
